import type { Metadata } from 'next'
import { Bokor, Montserrat, Raleway } from 'next/font/google'
import './globals.css'

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  style: ['normal'],
  variable: '--raleway-text',
})

const bokor = Bokor({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  variable: '--bokor-text',
})

export const metadata: Metadata = {
  title: {
    template: '%s | Karrot Market',
    default: 'Karrot market',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-auto mb-28 max-w-screen-sm bg-neutral-900 text-white ${bokor.variable} ${raleway.variable}`}
        // style={raleway.style}
      >
        {children}
      </body>
    </html>
  )
}
